name: fatiando-data-moon-gravity
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - numpy
  - jupyterlab
  - matplotlib
  - xarray
  - netcdf4
  - pyproj
  - pyshtools==4.10
  # PyGMT for plotting
  - pygmt==0.6.*
  - gmt==6.3.*
  - ipython
  # Fatiando
  - pooch>=1.0
  - harmonica==0.4.*
  - verde==1.7.*
  - boule==0.3.*
